Repository owncloud/calendar, pull requests merged in 2020-01, with the labels that each got.

#1055 makeFile modified
  .gitignore
  .php_cs.dist
  .travis.yml
  Makefile
  composer.json
  composer.lock
  gulpfile.js
  package.json
  phpunit.xml
  tests/js/config/karma.js
  tests/unit/controller/contactcontrollerTest.php
  tests/unit/controller/emailcontrollerTest.php
  tests/unit/controller/proxycontrollerTest.php
  tests/unit/controller/settingscontrollerTest.php
  tests/unit/controller/viewcontrollerTest.php
  tests/unit/http/streamresponseTest.php
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/php_codesniffer/composer.json
  yarn.lock
Labels: 3 - to review, QA-team

#1068 Add vendor-bin to .gitignore
  .gitignore
Labels: QA-team

#1074 run php unit tests in drone
  .drone.starlark
  .drone.yml
Labels: Drone, QA-team
