Repository owncloud/calendar, pull requests merged in 2020-02, with the labels that each got.

#1076 Adjusted wrong .jsinthrc path in the gulpfile
  gulpfile.js
Labels: 3 - to review

#1077 Update starlark code
  .drone.starlark
  .drone.yml
Labels: 3 - to review, Drone, QA-team

#1080 Recover makefile appstore
  Makefile
Labels: 3 - to review, QA-team

#1082 [Tests-only] run js tests on drone
  .drone.starlark
  .drone.yml
  Makefile
Labels: Drone, QA-team

#1083 convert .drone.starlark to .drone.star
  .drone.star
  .drone.yml
Labels: QA-team

#1084 Drop Travis and adjust build status badge to drone
  .travis.yml
  README.md
Labels: 3 - to review, Drone, QA-team
